name: Update readme ⭐️ progress

on:
    # !Please set a different minute than 51 if you enable this!
    schedule:
        - cron: "42 23 * * 0,4" # Runs at 23:42 on Sunday, Tuesday and Friday
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  ref: ${{ github.head_ref }}
            - uses: k2bd/advent-readme-stars@v1
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}
            - uses: stefanzweifel/git-auto-commit-action@v4
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  commit_message: "update readme progess"
